### ISSUE TITLE
Convert bibitems into BibTeX bib

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/KinectPaper2018#1]
For: "Improving Upper-Body Gesture Controls for Teacher Use" (submitted to International Journal of Human-Computer Studies)

Do we have the original bib?

[inputbib.txt](https://github.com/tomcrick/KinectPaper2018/files/1619421/inputbib.txt)

**Comment by jamcnaughton** [comment]
Found it, added it in 6acb579 as upperbodygestures.bib
